#!/bin/bash

# put this in your bspwmrc file to use this script on launch
pkill autofullscreen. || true && $HOME/.config/bspwm/scripts/autofullscreen.sh &
# parameters available: -d -l
# read script for more info
